/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

import hn.uth.poo.p3.negocios.clientes.ClienteNegocios;
import hn.uth.poo.p3.recursos.clases.Cliente;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class frmBuscador extends javax.swing.JFrame {

    /**
     * Creates new form frmBuscador
     */
    DefaultTableModel modelo;
    public frmBuscador() {
        initComponents();        
        Inicio();
    }
    public void Inicio(){
        modelo=(DefaultTableModel) tblDatos.getModel();  
        setSize(625, 596);
        setLocationRelativeTo(null);      
    }
    public void Leer(){
        try {
            List<Cliente> listaCliente=new ClienteNegocios().Leer();
            modelo.setRowCount(0);
            for (Cliente cliente : listaCliente) {
                Object registroLeido[]={cliente.getNombre(),cliente.getId()};
                modelo.addRow(registroLeido);
            }
            tblDatos.setModel(modelo);
        } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);      
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPlaca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        txtNomCliente = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDatos = new javax.swing.JTable();
        btnRegistrarCliente = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        btnLeer = new javax.swing.JButton();
        btnRegistrarCarro = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Consulta de los Clientes");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 280, 32);

        jLabel2.setFont(new java.awt.Font("MingLiU-ExtB", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Nombre del Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 160, 108, 15);

        jLabel3.setFont(new java.awt.Font("MingLiU-ExtB", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText(" No.ID Cliente");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 160, 84, 15);

        jLabel4.setFont(new java.awt.Font("MingLiU-ExtB", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("Marca del carro");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(260, 160, 90, 15);

        jLabel5.setFont(new java.awt.Font("MingLiU-ExtB", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("No. de Placa");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(390, 160, 80, 15);

        jLabel6.setFont(new java.awt.Font("MingLiU-ExtB", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setText("Color del Carro");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(510, 160, 90, 15);

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(370, 190, 110, 30);

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor);
        txtColor.setBounds(500, 190, 100, 30);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(260, 190, 99, 30);

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdCliente);
        txtIdCliente.setBounds(130, 190, 120, 30);

        txtNomCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomClienteActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomCliente);
        txtNomCliente.setBounds(10, 190, 110, 30);

        tblDatos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tblDatos.setFont(new java.awt.Font("Consolas", 0, 11)); // NOI18N
        tblDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Identidad", "Carro", "No. de Placa", "Color", "Imagen"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Integer.class, java.lang.Object.class, java.lang.Byte.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 350, 510, 152);

        btnRegistrarCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-check-file-16.png")); // NOI18N
        btnRegistrarCliente.setText("Registrar Cliente");
        btnRegistrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCliente);
        btnRegistrarCliente.setBounds(40, 240, 160, 25);

        btnEliminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-delete-document-16.png")); // NOI18N
        btnEliminar.setText("Eliminar Datos ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(300, 280, 123, 25);

        btnBuscar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-search-16.png")); // NOI18N
        btnBuscar.setText("Buscar Datos");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(410, 240, 115, 25);

        btnLeer.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-read-16.png")); // NOI18N
        btnLeer.setText("Leer Datos");
        btnLeer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeerActionPerformed(evt);
            }
        });
        getContentPane().add(btnLeer);
        btnLeer.setBounds(490, 290, 120, 25);

        btnRegistrarCarro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-car-badge-16.png")); // NOI18N
        btnRegistrarCarro.setText("Registrar Carro");
        btnRegistrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCarro);
        btnRegistrarCarro.setBounds(130, 300, 130, 23);

        btnActualizar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-refresh-16.png")); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(240, 230, 100, 25);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\geometrical-background-design_1078-66.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 620, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdClienteActionPerformed

    private void txtNomClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomClienteActionPerformed

    private void btnLeerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeerActionPerformed
        // TODO add your handling code here:
        Leer();
    }//GEN-LAST:event_btnLeerActionPerformed

    private void tblDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDatosMouseClicked
        // TODO add your handling code here:
        int filasSeleccionada=tblDatos.getSelectedRow();
        txtNomCliente.setText(modelo.getValueAt(filasSeleccionada, 0).toString());
        txtIdCliente.setText(modelo.getValueAt(filasSeleccionada, 1).toString());
//        txtMarca.setText(modelo.getValueAt(filasSeleccionada, lo2).toString());
//        txtPlaca.setText(modelo.getValueAt(filasSeleccionada, 3).toString());
//        txtColor.setText(modelo.getValueAt(filasSeleccionada, 4).toString());
    }//GEN-LAST:event_tblDatosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        int elijoBotonParaEliminar = JOptionPane.showConfirmDialog(null, "¿Desea eliminar?","Mensaje",JOptionPane.OK_CANCEL_OPTION);
        if(elijoBotonParaEliminar == 0){
            try {
                Cliente clientes=new Cliente();
                clientes.setNombre(txtNomCliente.getText());
                clientes.setId(Integer.parseInt(txtIdCliente.getText()));
                new ClienteNegocios().Eliminar(clientes);                
                Leer();
                JOptionPane.showMessageDialog(null, "Eliminado", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarClienteActionPerformed
        // TODO add your handling code here: 
//        frmClientes cliente=new frmClientes();
//        cliente.setVisible(true);
            try {
                Cliente clientes=new Cliente();
                clientes.setNombre(txtNomCliente.getText());
                clientes.setId(Integer.parseInt(txtIdCliente.getText()));
                String respuesta= new ClienteNegocios().Insertar(clientes);
                JOptionPane.showMessageDialog(null, "Guardado", "EXITO", JOptionPane.INFORMATION_MESSAGE);                              
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnRegistrarClienteActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        try {
                Cliente clientes=new Cliente();
                clientes.setNombre(txtNomCliente.getText());
                clientes.setId(Integer.parseInt(txtIdCliente.getText()));
                List<Cliente> listaCliente= new ClienteNegocios().Buscar(clientes);
                modelo.setRowCount(0);
                for (Cliente cliente : listaCliente) {
                    Object registroLeido[]={cliente.getNombre(),cliente.getId()};
                    modelo.addRow(registroLeido);
                }
                tblDatos.setModel(modelo);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        try {
                Cliente clientes=new Cliente();
                clientes.setNombre(txtNomCliente.getText());
                clientes.setId(Integer.parseInt(txtIdCliente.getText()));
                new ClienteNegocios().Actualizar(clientes);
                JOptionPane.showMessageDialog(null, "Actualizado", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                Leer();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnRegistrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCarroActionPerformed
        // TODO add your handling code here:
//        frmCarro carros=new frmCarro();
//        carros.setVisible(true);
            try {
            Cliente clientes=new Cliente();
            clientes.setNombre(txtNomCliente.getText());
            clientes.setId(Integer.parseInt(txtIdCliente.getText()));
            new ClienteNegocios().Leer();
            Leer();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_btnRegistrarCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmBuscador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLeer;
    private javax.swing.JButton btnRegistrarCarro;
    private javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JTable tblDatos;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtNomCliente;
    private javax.swing.JTextField txtPlaca;
    // End of variables declaration//GEN-END:variables
}
