/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

/**
 *
 * @author Dell
 */
public class frmCarro extends javax.swing.JFrame {

    /**
     * Creates new form frmCarro
     */
    public frmCarro() {
        initComponents();
        setSize(579, 429);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSeccionCarros = new javax.swing.JLabel();
        lblModelo = new javax.swing.JLabel();
        lblColorVehiculo = new javax.swing.JLabel();
        lblAnio = new javax.swing.JLabel();
        lblMarca = new javax.swing.JLabel();
        lblNumeroMotor = new javax.swing.JLabel();
        lblProblema = new javax.swing.JLabel();
        lblVIN = new javax.swing.JLabel();
        lblPlaca = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDiseño = new javax.swing.JLabel();
        txtMarca = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtPlaca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtAnio = new javax.swing.JTextField();
        txtNumeroMotor = new javax.swing.JTextField();
        txtVIN = new javax.swing.JTextField();
        dcFechaInicio = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDatos = new javax.swing.JTextArea();
        btnRegistrarCarro = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        lblSeccionCarros.setFont(new java.awt.Font("Rockwell", 1, 18)); // NOI18N
        lblSeccionCarros.setForeground(new java.awt.Color(255, 255, 255));
        lblSeccionCarros.setText("Seccion de Carros");
        getContentPane().add(lblSeccionCarros);
        lblSeccionCarros.setBounds(210, 20, 160, 24);

        lblModelo.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblModelo.setForeground(new java.awt.Color(255, 255, 255));
        lblModelo.setText("Modelo:");
        getContentPane().add(lblModelo);
        lblModelo.setBounds(50, 120, 44, 15);

        lblColorVehiculo.setFont(new java.awt.Font("Segoe UI Emoji", 1, 11)); // NOI18N
        lblColorVehiculo.setForeground(new java.awt.Color(255, 255, 255));
        lblColorVehiculo.setText("Color de su vehiculo:");
        getContentPane().add(lblColorVehiculo);
        lblColorVehiculo.setBounds(10, 55, 129, 12);

        lblAnio.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblAnio.setForeground(new java.awt.Color(255, 255, 255));
        lblAnio.setText("Año:");
        getContentPane().add(lblAnio);
        lblAnio.setBounds(60, 150, 25, 15);

        lblMarca.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblMarca.setForeground(new java.awt.Color(255, 255, 255));
        lblMarca.setText("Marca:");
        getContentPane().add(lblMarca);
        lblMarca.setBounds(50, 80, 35, 15);

        lblNumeroMotor.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNumeroMotor.setForeground(new java.awt.Color(255, 255, 255));
        lblNumeroMotor.setText("Numero del Motor:");
        getContentPane().add(lblNumeroMotor);
        lblNumeroMotor.setBounds(20, 180, 101, 15);

        lblProblema.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblProblema.setForeground(new java.awt.Color(255, 255, 255));
        lblProblema.setText("Describa el problema del auto");
        getContentPane().add(lblProblema);
        lblProblema.setBounds(360, 50, 155, 15);

        lblVIN.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblVIN.setForeground(new java.awt.Color(255, 255, 255));
        lblVIN.setText("VIN:");
        getContentPane().add(lblVIN);
        lblVIN.setBounds(50, 210, 22, 15);

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblPlaca.setForeground(new java.awt.Color(255, 255, 255));
        lblPlaca.setText("Placa:");
        getContentPane().add(lblPlaca);
        lblPlaca.setBounds(50, 240, 30, 15);

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblFecha.setForeground(new java.awt.Color(255, 255, 255));
        lblFecha.setText("Fecha de Inicio:");
        getContentPane().add(lblFecha);
        lblFecha.setBounds(30, 272, 80, 15);

        lblDiseño.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\mechanic-2111994-1776451.png")); // NOI18N
        getContentPane().add(lblDiseño);
        lblDiseño.setBounds(330, 200, 260, 230);

        txtMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMarcaActionPerformed(evt);
            }
        });
        getContentPane().add(txtMarca);
        txtMarca.setBounds(150, 80, 136, 20);

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });
        getContentPane().add(txtColor);
        txtColor.setBounds(150, 50, 136, 20);

        txtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlacaActionPerformed(evt);
            }
        });
        getContentPane().add(txtPlaca);
        txtPlaca.setBounds(150, 110, 136, 20);

        txtModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModeloActionPerformed(evt);
            }
        });
        getContentPane().add(txtModelo);
        txtModelo.setBounds(150, 140, 136, 20);

        txtAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnioActionPerformed(evt);
            }
        });
        getContentPane().add(txtAnio);
        txtAnio.setBounds(150, 170, 136, 20);

        txtNumeroMotor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroMotorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNumeroMotor);
        txtNumeroMotor.setBounds(150, 200, 136, 20);

        txtVIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVINActionPerformed(evt);
            }
        });
        getContentPane().add(txtVIN);
        txtVIN.setBounds(150, 230, 136, 20);
        getContentPane().add(dcFechaInicio);
        dcFechaInicio.setBounds(153, 260, 130, 30);

        txtaDatos.setColumns(20);
        txtaDatos.setRows(5);
        jScrollPane1.setViewportView(txtaDatos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 70, 220, 130);

        btnRegistrarCarro.setBackground(new java.awt.Color(204, 204, 204));
        btnRegistrarCarro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-thick-long-right-arrow-64.png")); // NOI18N
        btnRegistrarCarro.setBorder(null);
        btnRegistrarCarro.setContentAreaFilled(false);
        btnRegistrarCarro.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-thick-long-right-arrow-2.png")); // NOI18N
        btnRegistrarCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarCarroActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrarCarro);
        btnRegistrarCarro.setBounds(220, 310, 100, 70);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\3.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 579, 429);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMarcaActionPerformed

    private void txtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlacaActionPerformed

    private void txtModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModeloActionPerformed

    private void txtAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnioActionPerformed

    private void txtNumeroMotorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroMotorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroMotorActionPerformed

    private void txtVINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVINActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVINActionPerformed

    private void btnRegistrarCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarCarroActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_btnRegistrarCarroActionPerformed
    public void Limpiar(){
        txtAnio.setText("");
        txtColor.setText("");
        txtMarca.setText("");
        txtModelo.setText("");
        txtNumeroMotor.setText("");
        txtPlaca.setText("");
        txtVIN.setText("");
        txtaDatos.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCarro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCarro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarCarro;
    private com.toedter.calendar.JDateChooser dcFechaInicio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnio;
    private javax.swing.JLabel lblColorVehiculo;
    private javax.swing.JLabel lblDiseño;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblMarca;
    private javax.swing.JLabel lblModelo;
    private javax.swing.JLabel lblNumeroMotor;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JLabel lblProblema;
    private javax.swing.JLabel lblSeccionCarros;
    private javax.swing.JLabel lblVIN;
    private javax.swing.JTextField txtAnio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    private javax.swing.JTextField txtNumeroMotor;
    private javax.swing.JTextField txtPlaca;
    private javax.swing.JTextField txtVIN;
    private javax.swing.JTextArea txtaDatos;
    // End of variables declaration//GEN-END:variables
}
