/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

import hn.uth.poo.p3.negocios.clientes.ClienteNegocios;
import hn.uth.poo.p3.recursos.clases.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class frmClientes extends javax.swing.JFrame {

    /**
     * Creates new form frmClientes
     */
    frmBuscador leer;    
    public frmClientes() {
        initComponents();
        leer=new frmBuscador();
        setSize(471, 425);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrar = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtRtn = new javax.swing.JTextField();
        txtLicencia = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        lblTitulo = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblIdentidad = new javax.swing.JLabel();
        lblRtn = new javax.swing.JLabel();
        lblLicencia = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreo = new javax.swing.JLabel();
        Direccion = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        btnRegistrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-thick-long-right-arrow-64.png")); // NOI18N
        btnRegistrar.setText("Registrar");
        btnRegistrar.setRolloverIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-thick-long-right-arrow-2.png")); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(140, 340, 160, 40);

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(193, 38, 160, 30);

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        getContentPane().add(txtId);
        txtId.setBounds(193, 76, 160, 30);

        txtRtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRtnActionPerformed(evt);
            }
        });
        getContentPane().add(txtRtn);
        txtRtn.setBounds(193, 124, 160, 30);
        getContentPane().add(txtLicencia);
        txtLicencia.setBounds(193, 162, 160, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(190, 210, 160, 30);
        getContentPane().add(txtCorreo);
        txtCorreo.setBounds(190, 250, 160, 30);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(190, 290, 160, 30);

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setText("Sección Cliente");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(160, 10, 240, 20);

        lblNombre.setBackground(new java.awt.Color(0, 204, 204));
        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(104, 41, 46, 15);

        lblIdentidad.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        lblIdentidad.setText("Identidad:");
        getContentPane().add(lblIdentidad);
        lblIdentidad.setBounds(104, 76, 53, 15);

        lblRtn.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblRtn.setText("RTN:");
        getContentPane().add(lblRtn);
        lblRtn.setBounds(104, 124, 40, 18);

        lblLicencia.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblLicencia.setText("Licencia");
        getContentPane().add(lblLicencia);
        lblLicencia.setBounds(100, 160, 70, 30);

        lblTelefono.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblTelefono.setText("Telefono:");
        lblTelefono.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(90, 200, 80, 40);

        lblCorreo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        lblCorreo.setText("Correo");
        getContentPane().add(lblCorreo);
        lblCorreo.setBounds(100, 240, 60, 40);

        Direccion.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        Direccion.setText("Direccion");
        getContentPane().add(Direccion);
        Direccion.setBounds(90, 280, 80, 40);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\8.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, -40, 470, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        try {
                Cliente clientes=new Cliente();
                clientes.setNombre(txtNombre.getText());
                clientes.setId(Integer.parseInt(txtId.getText()));
                new ClienteNegocios().Insertar(clientes);
                JOptionPane.showMessageDialog(null, "Guardado", "EXITO", JOptionPane.INFORMATION_MESSAGE);
                leer.Leer();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        LimpiarCampos();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtRtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRtnActionPerformed
    public void LimpiarCampos(){    
        txtNombre.setText("");
        txtId.setText("");
        txtCorreo.setText("");
        txtDireccion.setText("");
        txtLicencia.setText("");
        txtRtn.setText("");
        txtTelefono.setText(""); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Direccion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel lblCorreo;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdentidad;
    private javax.swing.JLabel lblLicencia;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRtn;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtLicencia;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtRtn;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
