/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

/**
 *
 * @author Dell
 */
public class frmMecanico extends javax.swing.JFrame {

    /**
     * Creates new form frmMecanico
     */
    public frmMecanico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaDiagnostico = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaListRespuesto = new javax.swing.JTextArea();
        Diagnostico = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblListaRepuesto = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hn/uth/poo/p3/recursos/imagenes1/car-auto-mechanic-maintenance-automobile-repair-shop-clip-art-repair.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Rockwell", 1, 24)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(0, 51, 51));
        lblTitulo.setText("Mecánico");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(240, 30, 110, 32);

        lblFechaFinal.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        lblFechaFinal.setForeground(new java.awt.Color(0, 51, 51));
        lblFechaFinal.setText("Fecha Final:");
        getContentPane().add(lblFechaFinal);
        lblFechaFinal.setBounds(270, 250, 85, 19);

        txtaDiagnostico.setColumns(20);
        txtaDiagnostico.setRows(5);
        jScrollPane1.setViewportView(txtaDiagnostico);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 150, 166, 96);

        txtaListRespuesto.setColumns(20);
        txtaListRespuesto.setRows(5);
        jScrollPane2.setViewportView(txtaListRespuesto);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(390, 150, 166, 96);

        Diagnostico.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        Diagnostico.setForeground(new java.awt.Color(0, 51, 51));
        Diagnostico.setText("Diagnostico ");
        getContentPane().add(Diagnostico);
        Diagnostico.setBounds(80, 110, 87, 19);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(240, 290, 136, 20);

        lblListaRepuesto.setFont(new java.awt.Font("Levenim MT", 1, 14)); // NOI18N
        lblListaRepuesto.setForeground(new java.awt.Color(0, 51, 51));
        lblListaRepuesto.setText("Lista de repuestos");
        getContentPane().add(lblListaRepuesto);
        lblListaRepuesto.setBounds(410, 110, 131, 19);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\tuer.jpg")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(0, 0, 630, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMecanico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMecanico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Diagnostico;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblListaRepuesto;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextArea txtaDiagnostico;
    private javax.swing.JTextArea txtaListRespuesto;
    // End of variables declaration//GEN-END:variables
}
