/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.poo.p3.presentacion.gui;

import java.awt.Color;

/**
 *
 * @author Dell
 */
public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public frmPrincipal() {
        initComponents();
        this.getContentPane().setBackground(Color.BLACK);
        setSize(720, 554);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miBuscador = new javax.swing.JMenuItem();
        miRegistroCarro = new javax.swing.JMenuItem();
        miRegistroCliente = new javax.swing.JMenuItem();
        miAddPieza = new javax.swing.JMenuItem();
        miFactura = new javax.swing.JMenuItem();
        miSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblFondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\portada.png")); // NOI18N
        getContentPane().add(lblFondo);
        lblFondo.setBounds(120, 20, 730, 450);

        jMenu1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-folder-48.png")); // NOI18N
        jMenu1.setText("Archivos");

        miBuscador.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-search-16.png")); // NOI18N
        miBuscador.setText("Buscador");
        miBuscador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBuscadorActionPerformed(evt);
            }
        });
        jMenu1.add(miBuscador);

        miRegistroCarro.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-car-badge-24.png")); // NOI18N
        miRegistroCarro.setText("Registrar Carro");
        miRegistroCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroCarroActionPerformed(evt);
            }
        });
        jMenu1.add(miRegistroCarro);

        miRegistroCliente.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-car-badge-16.png")); // NOI18N
        miRegistroCliente.setText("Registrar Cliente");
        miRegistroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRegistroClienteActionPerformed(evt);
            }
        });
        jMenu1.add(miRegistroCliente);

        miAddPieza.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\pngocean.png")); // NOI18N
        miAddPieza.setText("Agregar Piezas");
        miAddPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miAddPiezaActionPerformed(evt);
            }
        });
        jMenu1.add(miAddPieza);

        miFactura.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\pngocean2.png")); // NOI18N
        miFactura.setText("Facturas");
        miFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miFacturaActionPerformed(evt);
            }
        });
        jMenu1.add(miFactura);

        miSalir.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-delete-document-16.png")); // NOI18N
        miSalir.setText("Salir");
        miSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miSalirActionPerformed(evt);
            }
        });
        jMenu1.add(miSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\icons8-car-48.png")); // NOI18N
        jMenu2.setText("Carros");

        jMenuItem7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\mecani.jpg")); // NOI18N
        jMenuItem7.setText("Mecanico");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Dell\\Documents\\proyecto2\\src\\main\\java\\hn\\uth\\poo\\p3\\recursos\\imagenes1\\ca copia.png")); // NOI18N
        jMenuItem8.setText("Servicios");
        jMenu2.add(jMenuItem8);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miRegistroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroClienteActionPerformed
        // TODO add your handling code here:
        frmClientes cliente=new frmClientes();
        cliente.setVisible(true);
    }//GEN-LAST:event_miRegistroClienteActionPerformed

    private void miSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_miSalirActionPerformed

    private void miBuscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBuscadorActionPerformed
        // TODO add your handling code here:
        frmBuscador buscador=new frmBuscador();
        buscador.setVisible(true);
    }//GEN-LAST:event_miBuscadorActionPerformed

    private void miRegistroCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRegistroCarroActionPerformed
        // TODO add your handling code here:
        frmCarro registroCarro=new frmCarro();
        registroCarro.setVisible(true);
    }//GEN-LAST:event_miRegistroCarroActionPerformed

    private void miAddPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miAddPiezaActionPerformed
        // TODO add your handling code here:
        frmBuscarPiezas buscoPieza=new frmBuscarPiezas();
        buscoPieza.setVisible(true);
    }//GEN-LAST:event_miAddPiezaActionPerformed

    private void miFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miFacturaActionPerformed
        // TODO add your handling code here:
        frmFactura factura=new frmFactura();
        factura.setVisible(true);
    }//GEN-LAST:event_miFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JMenuItem miAddPieza;
    private javax.swing.JMenuItem miBuscador;
    private javax.swing.JMenuItem miFactura;
    private javax.swing.JMenuItem miRegistroCarro;
    private javax.swing.JMenuItem miRegistroCliente;
    private javax.swing.JMenuItem miSalir;
    // End of variables declaration//GEN-END:variables
}
